---

- name: Install requisite packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3
    - python3-pip
    - dbus-python
    - dbus-x11
  become: yes

- name: Install Code42 CLI
  pip:
    name: code42cli
    executable: pip3
  become: yes

- name: Delete existing profiles
  expect:
    command: code42 profile delete-all
    responses:
      sure: y

- name: Create forwarder profile setting password interactively
  expect:
    command: code42 profile create --name "{{ profile }}" >
                                   --server "{{ server }}" >
                                   --username "{{ username }}"
    responses:
      password: y
      Password: "{{ secret }}"
      keyring: y

- name: Create a cron job to send security data to destination daily at midnight
  cron:
    name: forward-logs
    hour: "{{ hour }}"
    minute: "{{ minute }}"
    job: code42 security-data send-to "{{ destination }}" >
                                    -p "{{ protocol }}"
                                    -f "{{ format }}" >
                                    -b "{{ begin }}" >
                                    --profile "{{ profile }}" -i
